### ISSUE TITLE
when clustering option is k-means, KeyError: 'X_s'

### ISSUE THREAD

**Issue by rebpan** [imtiazziko/Variational-Fair-Clustering#1]
Traceback (most recent call last):
  File "C:\Users\ddd\Anaconda3\envs\VFC\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\ddd\Anaconda3\envs\VFC\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\ddd\Code\Variational-Fair-Clustering\src\fair_clustering.py", line 20, in kmeans_update
    X = utils.SHARED_VARS['X_s']
KeyError: 'X_s'

I find in multiprocessing, utils.SHARED_VARS variable becomes NULL

**Comment by rebpan** [comment]
There is a problem running on windows, it works fine on linux
